Repository nyu-devops-spring-2019/wishlists, pull requests merged in 2019-03, with the labels that each got.

#48 add package to the environment including pylint
  Vagrantfile
  service.py
Labels: help wanted

#49 Adding a requirements text file for Vagrant and an __init__.py file
  __init__.py
  requirements.txt
Labels: technical debt

#50 Made changes to service.py to add a main function
  service.py
Labels: bug

#51 Add .vagrant folder to ignore file
  .gitignore
Labels: bug

#63 add files to make structure similar to lab-flask-sqlalchemy
  .cfignore
  db/.keep
  manage.py
  manifest.yml
Labels: technical debt

#64 Making the files similar to lab-flask-sqlaclhemy
  Vagrantfile
  service.py
  setup.cfg
Labels: technical debt

#65 Other changes
  .cfignore
  .coveragerc
  .travis.yml
  Jenkinsfile
  Makefile
  Procfile
  Vagrantfile
  __init__.py
  app/__init__.py
  app/models.py
  app/server.py
  app/vcap_service.py
  config.py
  manage.py
  manifest.yml
  requirements.txt
Labels: technical debt
